DB_DRIVER=org.postgresql.Driver
DB_URL=jdbc:postgresql://localhost:5432/account_reservation
DB_USERNAME=postgres
DB_PASSWORD=1234

JPA_SHOW_SQL=true
HIBERNATE_DDL_AUTO=validate
HIBERNATE_FORMAT_SQL=true

LIQUIBASE_ENABLED=true
LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml

SERVER_PORT=8080

HIBERNATE_SQL_LOG_LEVEL=DEBUG
HIBERNATE_TYPE_LOG_LEVEL=TRACE